/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_samsung_slsi_spatchalgo_SPatchAlgorithmWrapper */

#ifndef _Included_com_samsung_slsi_hpatchalgo_HPatchAlgorithmWrapper
#define _Included_com_samsung_slsi_hpatchalgo_HPatchAlgorithmWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_samsung_slsi_spatchalgo_SPatchAlgorithmWrapper
 * Method:    getRespirationRateEstimation
 * Signature: ([I[FII)F
 */
JNIEXPORT jfloat JNICALL Java_com_samsung_slsi_hpatchalgo_HPatchAlgorithmWrapper_getRespirationRateEstimation
  (JNIEnv *, jclass, jintArray, jfloatArray, jint, jint);

/*
 * Class:     com_samsung_slsi_spatchalgo_SPatchAlgorithmWrapper
 * Method:    getECGHeartRate
 * Signature: (I[III)I
 */
JNIEXPORT jint JNICALL Java_com_samsung_slsi_hpatchalgo_HPatchAlgorithmWrapper_getECGHeartRate
  (JNIEnv *, jclass, jint, jintArray, jint, jint);

/*
 * Class:     com_samsung_slsi_spatchalgo_SPatchAlgorithmWrapper
 * Method:    getECGHeartRateVariability
 * Signature: (I[IIII)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_samsung_slsi_hpatchalgo_HPatchAlgorithmWrapper_getECGHeartRateVariability
  (JNIEnv *, jclass, jint, jintArray, jint, jint, jint);

/*
 * Class:     com_samsung_slsi_spatchalgo_SPatchAlgorithmWrapper
 * Method:    getLeadOnOff
 * Signature: ([FIIF)Z
 */
JNIEXPORT jboolean JNICALL Java_com_samsung_slsi_hpatchalgo_HPatchAlgorithmWrapper_getLeadOnOff
  (JNIEnv *, jclass, jfloatArray, jint, jint, jfloat);

/*
 * Class:     com_samsung_slsi_spatchalgo_SPatchAlgorithmWrapper
 * Method:    ecgFitnessCreateFitinfo
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_samsung_slsi_hpatchalgo_HPatchAlgorithmWrapper_ecgFitnessCreateFitinfo
  (JNIEnv *, jclass);

/*
 * Class:     com_samsung_slsi_spatchalgo_SPatchAlgorithmWrapper
 * Method:    ecgFitnessDestroyFitinfo
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_samsung_slsi_hpatchalgo_HPatchAlgorithmWrapper_ecgFitnessDestroyFitinfo
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_samsung_slsi_spatchalgo_SPatchAlgorithmWrapper
 * Method:    ecgFitnessGetHRmax
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_samsung_slsi_hpatchalgo_HPatchAlgorithmWrapper_ecgFitnessGetHRmax
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_samsung_slsi_spatchalgo_SPatchAlgorithmWrapper
 * Method:    ecgFitnessGetHRrest
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_samsung_slsi_hpatchalgo_HPatchAlgorithmWrapper_ecgFitnessGetHRrest
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_samsung_slsi_spatchalgo_SPatchAlgorithmWrapper
 * Method:    ecgFitnessGetpctHR
 * Signature: (JII)F
 */
JNIEXPORT jfloat JNICALL Java_com_samsung_slsi_hpatchalgo_HPatchAlgorithmWrapper_ecgFitnessGetpctHR
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     com_samsung_slsi_spatchalgo_SPatchAlgorithmWrapper
 * Method:    ecgFitnessGetSportsZone
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_samsung_slsi_hpatchalgo_HPatchAlgorithmWrapper_ecgFitnessGetSportsZone
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_samsung_slsi_spatchalgo_SPatchAlgorithmWrapper
 * Method:    ecgFitnessGetMaxAvailableHR
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_com_samsung_slsi_hpatchalgo_HPatchAlgorithmWrapper_ecgFitnessGetMaxAvailableHR
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_samsung_slsi_spatchalgo_SPatchAlgorithmWrapper
 * Method:    ecgFitnessGetEnergyExpenditure
 * Signature: (JFIIIF)F
 */
JNIEXPORT jfloat JNICALL Java_com_samsung_slsi_hpatchalgo_HPatchAlgorithmWrapper_ecgFitnessGetEnergyExpenditure
  (JNIEnv *, jclass, jlong, jfloat, jint, jint, jint, jfloat);

#ifdef __cplusplus
}
#endif
#endif
